/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userPackage;

import adminPackage.loginadmin;
import java.awt.Color;
/**
 *
 * @author Salma
 */
public class EntryForm extends javax.swing.JFrame {

	/**
	 * Creates new form EntryForm
	 */
	public EntryForm() {
		initComponents();
		
		//GUI related code *ignore*
		adminBtn.setBackground(new Color(255, 255, 255, 255));
		userBtn.setBackground(new Color(255, 255, 255, 255));

	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accessPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminBtn = new javax.swing.JButton();
        userBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accessPanel.setBackground(new java.awt.Color(255, 255, 255));
        accessPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userPackage/drPhotoRESIZED.png"))); // NOI18N
        accessPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, -1));

        adminBtn.setBackground(new java.awt.Color(255, 255, 255));
        adminBtn.setText("Admin");
        adminBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });
        accessPanel.add(adminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 280, 53));

        userBtn.setText("User");
        userBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        accessPanel.add(userBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 400, 280, 53));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userPackage/userResized.png"))); // NOI18N
        accessPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 270, 250));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userPackage/resizedAdmin.png"))); // NOI18N
        accessPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 270, 250));

        getContentPane().add(accessPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        // TODO add your handling code here:
       		new loginadmin().setVisible(true);

    }//GEN-LAST:event_adminBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new EntryForm().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accessPanel;
    private javax.swing.JButton adminBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton userBtn;
    // End of variables declaration//GEN-END:variables
}
