/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userPackage;

import adminPackage.DatabaseConnectionDoc;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Fayroz Tarek
 */
public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     */
    
    UserData udata;
    UserBuilder userBuilder;
    User user;
    
    public UserProfile() {
        initComponents();
		//GUI related *ignore*
        lbl_img.setIcon(new ImageIcon("D:\\Software_Engineering\\Semester_6\\Design patterns\\Project\\DoctorFinderProject\\src\\main\\java\\com\\mycompany\\doctorFinder\\user\\pp2.png"));
        panel_homepage.setVisible(true);
        panel_chngInfo.setVisible(false);
        panel_chngPass.setVisible(false);
        panel_appointments.setVisible(false);
        panel_payments.setVisible(false);
	btn_out.setBackground(Color.white);
        btn_update.setBackground(Color.white);
        
        //Intialize vars
        udata = new UserData();
        userBuilder = new UserBuilder();
        user = userBuilder.createUser();

        //Intializing user info
        user = udata.getCertainUser(UserLogin.userID);
        
        if(user != null){
            lbl_name.setText(user.getName() + " " + user.getLname());    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jSplitPane1 = new javax.swing.JSplitPane();
        panel_Profile = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_homepage = new javax.swing.JLabel();
        lbl_chnginfo1 = new javax.swing.JLabel();
        lbl_chngPass = new javax.swing.JLabel();
        lbl_Appoin = new javax.swing.JLabel();
        lbl_payments = new javax.swing.JLabel();
        btn_out = new javax.swing.JButton();
        lbl_img = new javax.swing.JLabel();
        panel_homepage = new javax.swing.JPanel();
        panel_chngInfo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        panel_chngPass = new javax.swing.JPanel();
        panel_appointments = new javax.swing.JPanel();
        panel_payments = new javax.swing.JPanel();
        Amount_lbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Pay_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Lname_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Amount_txt = new javax.swing.JTextField();
        CardNo_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fname_txt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        Verify_btn = new javax.swing.JButton();
        cvv_txt = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerSize(1);

        panel_Profile.setBackground(new java.awt.Color(102, 204, 255));
        panel_Profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name.setText("User   Name");
        lbl_name.setAlignmentX(0.5F);
        panel_Profile.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, 31));

        lbl_homepage.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 22)); // NOI18N
        lbl_homepage.setText("Home Page");
        lbl_homepage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_homepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homepageMouseClicked(evt);
            }
        });
        panel_Profile.add(lbl_homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 191, -1));

        lbl_chnginfo1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 22)); // NOI18N
        lbl_chnginfo1.setText("Change Info");
        lbl_chnginfo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_chnginfo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_chnginfo1MouseClicked(evt);
            }
        });
        panel_Profile.add(lbl_chnginfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 191, -1));

        lbl_chngPass.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 22)); // NOI18N
        lbl_chngPass.setText("Change Password");
        lbl_chngPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_chngPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_chngPassMouseClicked(evt);
            }
        });
        panel_Profile.add(lbl_chngPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 191, -1));

        lbl_Appoin.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 22)); // NOI18N
        lbl_Appoin.setText("Appointments");
        lbl_Appoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Appoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_AppoinMouseClicked(evt);
            }
        });
        panel_Profile.add(lbl_Appoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 200, 30));

        lbl_payments.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 22)); // NOI18N
        lbl_payments.setText("Payments");
        lbl_payments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_payments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_paymentsMouseClicked(evt);
            }
        });
        panel_Profile.add(lbl_payments, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 191, -1));

        btn_out.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        btn_out.setForeground(new java.awt.Color(8, 128, 176));
        btn_out.setText("Logout");
        btn_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outActionPerformed(evt);
            }
        });
        panel_Profile.add(btn_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 760, 130, 40));

        lbl_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userPackage/pp2.png"))); // NOI18N
        panel_Profile.add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 110));

        jSplitPane1.setLeftComponent(panel_Profile);

        panel_homepage.setBackground(new java.awt.Color(255, 255, 255));
        panel_homepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_chngInfo.setBackground(new java.awt.Color(204, 255, 255));
        panel_chngInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel5.setText("First Name");
        panel_chngInfo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 119, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panel_chngInfo.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 189, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel6.setText("Gender");
        panel_chngInfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 119, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        panel_chngInfo.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 189, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel7.setText("Phone No2");
        panel_chngInfo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 119, 30));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panel_chngInfo.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 189, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel8.setText("Email");
        panel_chngInfo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 119, 30));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        panel_chngInfo.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 189, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        panel_chngInfo.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 189, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel9.setText("Address");
        panel_chngInfo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 119, 30));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        panel_chngInfo.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 189, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel10.setText("Phone No1");
        panel_chngInfo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 119, 30));
        panel_chngInfo.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 189, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel11.setText("Last Name");
        panel_chngInfo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 119, 30));

        btn_update.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        btn_update.setForeground(new java.awt.Color(8, 128, 176));
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        panel_chngInfo.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 203, 53));

        panel_homepage.add(panel_chngInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 810));

        panel_chngPass.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout panel_chngPassLayout = new javax.swing.GroupLayout(panel_chngPass);
        panel_chngPass.setLayout(panel_chngPassLayout);
        panel_chngPassLayout.setHorizontalGroup(
            panel_chngPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
        );
        panel_chngPassLayout.setVerticalGroup(
            panel_chngPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );

        panel_homepage.add(panel_chngPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel_appointments.setBackground(new java.awt.Color(204, 255, 153));

        javax.swing.GroupLayout panel_appointmentsLayout = new javax.swing.GroupLayout(panel_appointments);
        panel_appointments.setLayout(panel_appointmentsLayout);
        panel_appointmentsLayout.setHorizontalGroup(
            panel_appointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
        );
        panel_appointmentsLayout.setVerticalGroup(
            panel_appointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        panel_homepage.add(panel_appointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel_payments.setBackground(new java.awt.Color(255, 255, 51));

        Amount_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Amount_lbl.setText("Amount");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("CVV");

        Pay_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pay_btn.setText("Pay");
        Pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pay_btnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Payment");

        Lname_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lname_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lname_txtMouseClicked(evt);
            }
        });
        Lname_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Lname_txtKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Card Number");

        Amount_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Amount_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Amount_txtActionPerformed(evt);
            }
        });

        CardNo_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CardNo_txt.setText("xxxx-xxxx-xxxx-xxxx");
        CardNo_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CardNo_txtMouseClicked(evt);
            }
        });
        CardNo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CardNo_txtKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Last Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Expiration Date");

        Fname_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Fname_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fname_txtMouseClicked(evt);
            }
        });
        Fname_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Fname_txtKeyTyped(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        Verify_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Verify_btn.setText("Verify");
        Verify_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Verify_btnMouseClicked(evt);
            }
        });
        Verify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Verify_btnActionPerformed(evt);
            }
        });

        cvv_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cvv_txt.setText("xxx");
        cvv_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cvv_txtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_paymentsLayout = new javax.swing.GroupLayout(panel_payments);
        panel_payments.setLayout(panel_paymentsLayout);
        panel_paymentsLayout.setHorizontalGroup(
            panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paymentsLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_paymentsLayout.createSequentialGroup()
                .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_paymentsLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel3))
                    .addGroup(panel_paymentsLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CardNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(Lname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_paymentsLayout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cvv_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(panel_paymentsLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Fname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))))
                    .addGroup(panel_paymentsLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_paymentsLayout.createSequentialGroup()
                                .addComponent(Amount_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(Amount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119))
                            .addComponent(Pay_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Verify_btn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(501, Short.MAX_VALUE))
        );
        panel_paymentsLayout.setVerticalGroup(
            panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paymentsLayout.createSequentialGroup()
                .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_paymentsLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CardNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cvv_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_paymentsLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel4)))
                .addGap(41, 41, 41)
                .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(26, 26, 26)
                .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(Verify_btn)
                .addGap(47, 47, 47)
                .addGroup(panel_paymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amount_lbl)
                    .addComponent(Amount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(Pay_btn)
                .addGap(27, 27, 27))
        );

        panel_homepage.add(panel_payments, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSplitPane1.setRightComponent(panel_homepage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_btn_updateActionPerformed

    private void lbl_homepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homepageMouseClicked
        // TODO add your handling code here:
        panel_homepage.setVisible(true);
        panel_payments.setVisible(false);
        panel_appointments.setVisible(false);
        panel_chngPass.setVisible(false);
        panel_chngInfo.setVisible(false);
    }//GEN-LAST:event_lbl_homepageMouseClicked

    private void lbl_chnginfo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_chnginfo1MouseClicked
        // TODO add your handling code here:
        panel_chngInfo.setVisible(true);
    }//GEN-LAST:event_lbl_chnginfo1MouseClicked

    private void lbl_chngPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_chngPassMouseClicked
        // TODO add your handling code here:
        panel_chngPass.setVisible(true);
        panel_chngInfo.setVisible(false);

    }//GEN-LAST:event_lbl_chngPassMouseClicked

    private void lbl_AppoinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AppoinMouseClicked
        // TODO add your handling code here:
        panel_appointments.setVisible(true);
        panel_chngPass.setVisible(false);
        panel_chngInfo.setVisible(false);

    }//GEN-LAST:event_lbl_AppoinMouseClicked

    private void lbl_paymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_paymentsMouseClicked
        // TODO add your handling code here:
        panel_payments.setVisible(true);
        panel_appointments.setVisible(false);
        panel_chngPass.setVisible(false);
        panel_chngInfo.setVisible(false);

    }//GEN-LAST:event_lbl_paymentsMouseClicked

    private void btn_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outActionPerformed
        // TODO add your handling code here:
        UserLogin userLogin = new UserLogin();
        userLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_outActionPerformed

    private void Pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pay_btnActionPerformed

        JOptionPane.showMessageDialog(this,Amount_txt.getText()+ "has been Withdrawed");
    }//GEN-LAST:event_Pay_btnActionPerformed

    private void Lname_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lname_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Lname_txtMouseClicked

    private void Lname_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Lname_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Lname_txtKeyTyped

    private void Amount_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Amount_txtActionPerformed

    }//GEN-LAST:event_Amount_txtActionPerformed

    private void CardNo_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardNo_txtMouseClicked
        CardNo_txt.setText(null);
    }//GEN-LAST:event_CardNo_txtMouseClicked

    private void CardNo_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CardNo_txtKeyTyped

    }//GEN-LAST:event_CardNo_txtKeyTyped

    private void Fname_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fname_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Fname_txtMouseClicked

    private void Fname_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fname_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Fname_txtKeyTyped

    private void Verify_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Verify_btnMouseClicked

    }//GEN-LAST:event_Verify_btnMouseClicked

    private void Verify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Verify_btnActionPerformed

        String card,cvv;
        card = CardNo_txt.getText();
        cvv= cvv_txt.getText();
        if(card.length()>16 || card.length()<16)
        {
            JOptionPane.showMessageDialog(this, "Unvalid Number");
        }
        if(cvv.length()>3 || cvv.length()<3)
        {
            JOptionPane.showMessageDialog(this, "Unvalid Number");

        }

        try {
            Connection conn = DatabaseConnectionDoc.setConnection();
            String fname = Fname_txt.getText();
            String lname = Lname_txt.getText();
            //String Amount = Lname_txt.getText();
            String sql2 = "select fees from doctors where Fname = '"+fname+"' and Lname = '"+lname+"'  ";
            Statement stt = conn.createStatement();
            ResultSet rss = stt.executeQuery(sql2);
            if(rss.next())
            {
                dispose();
                //JOptionPane.showMessageDialog(this, "Welcome");

                Amount_txt.setText(Integer.toString(rss.getInt("fees")));
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }

        /*
        try {
            Connection con = DatabaseConnectionDoc.setConnection();
            String fname = Fname_txt.getText();
            String lname = Lname_txt.getText();
            String sql = "select * from User1 where Fname = '"+fname+"' and Lname = '"+lname+"'  ";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next())
            {
                dispose();
                //JOptionPane.showMessageDialog(this, "Welcome");
                Amount_lbl.setVisible(true);
                Amount_txt.setVisible(true);
                Pay_btn.setVisible(true);
                //Amount_txt.setText(Integer.toString(rs.getInt("fees")));

            }
            else
            {
                JOptionPane.showMessageDialog(this, "User not found");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
        */

    }//GEN-LAST:event_Verify_btnActionPerformed

    private void cvv_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvv_txtMouseClicked
        cvv_txt.setText(null);
    }//GEN-LAST:event_cvv_txtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount_lbl;
    private javax.swing.JTextField Amount_txt;
    private javax.swing.JTextField CardNo_txt;
    private javax.swing.JTextField Fname_txt;
    private javax.swing.JTextField Lname_txt;
    private javax.swing.JButton Pay_btn;
    private javax.swing.JButton Verify_btn;
    private javax.swing.JButton btn_out;
    private javax.swing.JButton btn_update;
    private javax.swing.JTextField cvv_txt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lbl_Appoin;
    private javax.swing.JLabel lbl_chngPass;
    private javax.swing.JLabel lbl_chnginfo1;
    private javax.swing.JLabel lbl_homepage;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_payments;
    private javax.swing.JPanel panel_Profile;
    private javax.swing.JPanel panel_appointments;
    private javax.swing.JPanel panel_chngInfo;
    private javax.swing.JPanel panel_chngPass;
    private javax.swing.JPanel panel_homepage;
    private javax.swing.JPanel panel_payments;
    // End of variables declaration//GEN-END:variables
}
