/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userPackage;

import javax.swing.JOptionPane;
import adminPackage.DatabaseConnectionDoc;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DELL
 */
public class UserPayment extends javax.swing.JFrame {

    
    /**
     * Creates new form UserPayment
     */
    public UserPayment() {
        initComponents();
        Amount_lbl.setVisible(false);
         Amount_txt.setVisible(false);
          Pay_btn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pay_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CardNo_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        Verify_btn = new javax.swing.JButton();
        cvv_txt = new javax.swing.JTextField();
        Amount_lbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Lname_txt = new javax.swing.JTextField();
        Amount_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Fname_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pay_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pay_btn.setText("Pay");
        Pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pay_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Payment");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Card Number");

        CardNo_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CardNo_txt.setText("xxxx-xxxx-xxxx-xxxx");
        CardNo_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CardNo_txtMouseClicked(evt);
            }
        });
        CardNo_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CardNo_txtKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Expiration Date");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        Verify_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Verify_btn.setText("Verify");
        Verify_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Verify_btnMouseClicked(evt);
            }
        });
        Verify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Verify_btnActionPerformed(evt);
            }
        });

        cvv_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cvv_txt.setText("xxx");
        cvv_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cvv_txtMouseClicked(evt);
            }
        });

        Amount_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Amount_lbl.setText("Amount");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("CVV");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("First Name");

        Lname_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lname_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lname_txtMouseClicked(evt);
            }
        });
        Lname_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Lname_txtKeyTyped(evt);
            }
        });

        Amount_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Amount_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Amount_txtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Last Name");

        Fname_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Fname_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fname_txtMouseClicked(evt);
            }
        });
        Fname_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Fname_txtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CardNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(Lname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cvv_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Fname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Amount_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(Amount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119))
                            .addComponent(Pay_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Verify_btn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CardNo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cvv_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel4)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(Verify_btn)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amount_lbl)
                    .addComponent(Amount_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(Pay_btn)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pay_btnActionPerformed

        JOptionPane.showMessageDialog(this,Amount_txt.getText()+ "has been Withdrawed");
    }//GEN-LAST:event_Pay_btnActionPerformed

    private void CardNo_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardNo_txtMouseClicked
        CardNo_txt.setText(null);
    }//GEN-LAST:event_CardNo_txtMouseClicked

    private void CardNo_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CardNo_txtKeyTyped

    }//GEN-LAST:event_CardNo_txtKeyTyped

    private void Verify_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Verify_btnMouseClicked
       
    }//GEN-LAST:event_Verify_btnMouseClicked

    private void Verify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Verify_btnActionPerformed
        
            String card,cvv;
            card = CardNo_txt.getText();
            cvv= cvv_txt.getText();
            if(card.length()>16 || card.length()<16)
            {
                JOptionPane.showMessageDialog(this, "Unvalid Number");
            } 
            if(cvv.length()>3 || cvv.length()<3)
            {
                JOptionPane.showMessageDialog(this, "Unvalid Number");
                
            } 
            
            try {
            Connection conn = DatabaseConnectionDoc.setConnection();
            String fname = Fname_txt.getText();
            String lname = Lname_txt.getText();
            //String Amount = Lname_txt.getText();
            String sql2 = "select fees from doctors where Fname = '"+fname+"' and Lname = '"+lname+"'  ";
            Statement stt = conn.createStatement();
            ResultSet rss = stt.executeQuery(sql2);
            if(rss.next())
            {
                dispose();
                //JOptionPane.showMessageDialog(this, "Welcome");
                
                 Amount_txt.setText(Integer.toString(rss.getInt("fees")));
            }
            
                 } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
          }
            
            /*
           try {
            Connection con = DatabaseConnectionDoc.setConnection();
            String fname = Fname_txt.getText();
            String lname = Lname_txt.getText();
            String sql = "select * from User1 where Fname = '"+fname+"' and Lname = '"+lname+"'  ";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next())
            {
                dispose();
                //JOptionPane.showMessageDialog(this, "Welcome");
                 Amount_lbl.setVisible(true);
                 Amount_txt.setVisible(true);
                 Pay_btn.setVisible(true);
                 //Amount_txt.setText(Integer.toString(rs.getInt("fees")));
                 
          
            }
            else
            {
                JOptionPane.showMessageDialog(this, "User not found");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
        }
            */
        
    }//GEN-LAST:event_Verify_btnActionPerformed

    private void Lname_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lname_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Lname_txtMouseClicked

    private void Lname_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Lname_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Lname_txtKeyTyped

    private void Amount_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Amount_txtActionPerformed

    }//GEN-LAST:event_Amount_txtActionPerformed

    private void cvv_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvv_txtMouseClicked
        cvv_txt.setText(null);
    }//GEN-LAST:event_cvv_txtMouseClicked

    private void Fname_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fname_txtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Fname_txtMouseClicked

    private void Fname_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fname_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Fname_txtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount_lbl;
    private javax.swing.JTextField Amount_txt;
    private javax.swing.JTextField CardNo_txt;
    private javax.swing.JTextField Fname_txt;
    private javax.swing.JTextField Lname_txt;
    private javax.swing.JButton Pay_btn;
    private javax.swing.JButton Verify_btn;
    private javax.swing.JTextField cvv_txt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
