/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userPackage;

import javax.swing.JOptionPane;
import adminPackage.DatabaseConnectionDoc;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class UserPayment extends javax.swing.JFrame {

    
    /**
     * Creates new form UserPayment
     */
    public UserPayment() {
        initComponents();
      
    }
/*public void tableDetails()
{
    DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
    dtm.setRowCount(0);
    String id = IdTxt.getText();
    try 
    {
        Connection con = DatabaseConnectionDoc.setConnection();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("select * from user1 where id=' "+id+"'");
        while(rs.next())
        {
            dtm.addRow(new Object[] {rs.getString(2) , rs.getString(3)});
            
        }
    }
    catch (Exception e )
    {
        JOptionPane.showMessageDialog(null, e);
    }
    
    
}*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        exYearText = new javax.swing.JTextField();
        cardNumberText = new javax.swing.JTextField();
        exMonth = new javax.swing.JComboBox<String>();
        secCodeText = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        payBtn = new javax.swing.JButton();
        detailsPaymentPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        creditRadBtn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        DocTxt = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        cashRadBtn2 = new javax.swing.JRadioButton();
        CurrCombo = new javax.swing.JComboBox();
        FeesTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel9.setText("Card Number");

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel10.setText("Expiry Month");

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel11.setText("Security Code ");

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel12.setText("Expiry Year");

        exYearText.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N

        cardNumberText.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N

        exMonth.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        exMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        exMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exMonthActionPerformed(evt);
            }
        });

        secCodeText.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 33)); // NOI18N
        jLabel16.setText("Card Information");

        payBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        payBtn.setText("Pay ");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(99, 99, 99)
                                    .addComponent(jLabel10))
                                .addComponent(cardNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(exYearText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(exMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(secCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 33, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(payBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(cardNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(secCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(payBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1285, 1285, 1285))
        );

        detailsPaymentPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel4.setText("Doctor ID :");

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 34)); // NOI18N
        jLabel6.setText("User Details");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 33)); // NOI18N
        jLabel3.setText("Payment Method");

        creditRadBtn.setBackground(new java.awt.Color(255, 255, 255));
        creditRadBtn.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        creditRadBtn.setSelected(true);
        creditRadBtn.setText("Credit Card");
        creditRadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditRadBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel7.setText("Fees");

        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N

        SearchBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        cashRadBtn2.setBackground(new java.awt.Color(255, 255, 255));
        cashRadBtn2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        cashRadBtn2.setText("Cash");
        cashRadBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRadBtn2ActionPerformed(evt);
            }
        });

        CurrCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EgyPound", "Dollar" }));
        CurrCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrComboActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel5.setText("ID :");

        javax.swing.GroupLayout detailsPaymentPanelLayout = new javax.swing.GroupLayout(detailsPaymentPanel);
        detailsPaymentPanel.setLayout(detailsPaymentPanelLayout);
        detailsPaymentPanelLayout.setHorizontalGroup(
            detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsPaymentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(539, 539, 539))
            .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                        .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(cashRadBtn2))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(creditRadBtn)
                        .addGap(246, 246, 246))
                    .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                        .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                                .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                                        .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                                                .addGap(218, 218, 218)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                                                .addGap(87, 87, 87)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FeesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CurrCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                                        .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(DocTxt)
                                            .addComponent(IDtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                                        .addGap(32, 32, 32)
                                        .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        detailsPaymentPanelLayout.setVerticalGroup(
            detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchBtn)
                            .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsPaymentPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                        .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                                .addComponent(creditRadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(67, 67, 67)
                                .addGroup(detailsPaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE))
                            .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FeesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CurrCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel22)
                        .addContainerGap())
                    .addGroup(detailsPaymentPanelLayout.createSequentialGroup()
                        .addComponent(cashRadBtn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(80, 80, 80))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(detailsPaymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(detailsPaymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(341, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creditRadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditRadBtnActionPerformed
        // TODO add your handling code here:
        String securityCode = new String(secCodeText.getPassword());
        if ((creditRadBtn.isSelected())&&(cardNumberText.getText().isEmpty() ||exYearText.getText().isEmpty()|| securityCode.isEmpty())){
            cardNumberText.setEditable(true);
            exYearText.setEditable(true);
            exMonth.setEditable(true);
            secCodeText.setEditable(true);
            JOptionPane.showMessageDialog(this, "Your data is incomplete.");
        }
    }//GEN-LAST:event_creditRadBtnActionPerformed

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_payBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
       // tableDetails();
        int checkId = 0;
        int Userid = Integer.parseInt(IDtxt.getText());
        int docId = Integer.parseInt(DocTxt.getText());
        try {
            Connection con = DatabaseConnectionDoc.setConnection();
            Statement st = con.createStatement();
            Statement st2 = con.createStatement();
            ResultSet rs = st.executeQuery("select patiet_id , doctor_id from appointments where patient_id= "+Userid+"");
            ResultSet rs1 = st.executeQuery("select fees from doctors where id= "+docId+"");
             while(rs.next())
        {
            int fees = rs1.getInt("fees");
            FeesTxt.setText(String.valueOf(fees));
            
             checkId = 1;
              IDtxt.setEditable(false);
              JOptionPane.showMessageDialog(this , "User exists!");

        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
        
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void exMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exMonthActionPerformed

    private void cashRadBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRadBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashRadBtn2ActionPerformed

    private void CurrComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrComboActionPerformed
        // TODO add your handling code here:
        String selectedItem = CurrCombo.getSelectedItem().toString();
        CurrDollars curr = new CurrDollars();
        double fees = Double.parseDouble(FeesTxt.getText());
        double value = curr.money(selectedItem, fees);
        FeesTxt.setText(String.valueOf(value));
        
    }//GEN-LAST:event_CurrComboActionPerformed

    public void ValidateCardNumber(){
		if(cardNumberText.getText().length() != 16 && creditRadBtn.isSelected()){
			JOptionPane.showMessageDialog(this, "Invalid Card Number."+ "\n"+ "Please check again.");	
		}
	}
	//it gives an exception if nothing was entered in the field "NumberFormatException"
	public void ValidateExpiryYear(){
		int exYear = Integer.parseInt(exYearText.getText());
		//no max expiry year
		try{
		if (exYear < 2022){
			JOptionPane.showMessageDialog(this, "Invalid Expiry date.");
		}
		}catch(NumberFormatException nfe){
			System.out.println(nfe.getMessage());
		}
	}
	
	public void ValidateSecurityCode(){
		String securityCode = new String(secCodeText.getPassword());
		if (securityCode.length() != 3){
			JOptionPane.showMessageDialog(this, "Invalid Security Code. Please check again.");
		} 
	}
	
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CurrCombo;
    private javax.swing.JTextField DocTxt;
    private javax.swing.JTextField FeesTxt;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField cardNumberText;
    private javax.swing.JRadioButton cashRadBtn2;
    private javax.swing.JRadioButton creditRadBtn;
    private javax.swing.JPanel detailsPaymentPanel;
    private javax.swing.JComboBox<String> exMonth;
    private javax.swing.JTextField exYearText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton payBtn;
    private javax.swing.JPasswordField secCodeText;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton submitBtn1;
    private javax.swing.JButton submitBtn2;
    // End of variables declaration//GEN-END:variables
}
