/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminPackage;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Salma
 */
public class admin_change_pass extends javax.swing.JFrame {

	/**
	 * Creates new form admin_change_pass
	 */
	public admin_change_pass() {
		initComponents();
		UIManager.put("OptionPane.messageFont", new Font("Microsoft JhengHei UI", Font.PLAIN, 18));
		updatebtn4.setBackground(Color.white);
		clearbtn4.setBackground(Color.white);
	}
	public void validateField()
    {
        String oldpass = oldPass_txt.getText();
        String newpass = passNew_txt.getText();
        String confirmpass = confirmPass_txt.getText();
        if(!oldpass.equals("") && !newpass.equals("") && !confirmpass.equals("") && newpass.equals(confirmpass))
        {
            updatebtn.setEnabled(true);
        }
        else
        {
            updatebtn.setEnabled(false);
        }
    }
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        confirmPass_txt4 = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        oldPass_txt4 = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        updatebtn4 = new javax.swing.JButton();
        passNew_txt4 = new javax.swing.JPasswordField();
        user_txt4 = new javax.swing.JTextField();
        clearbtn4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(488, 674));
        setSize(new java.awt.Dimension(488, 674));

        jPanel4.setBackground(new java.awt.Color(8, 128, 176));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reseet Pass", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel4.setMinimumSize(new java.awt.Dimension(488, 650));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Old password");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        confirmPass_txt4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        confirmPass_txt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmPass_txt4KeyReleased(evt);
            }
        });
        jPanel4.add(confirmPass_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 199, -1));

        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("New Password");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        oldPass_txt4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        oldPass_txt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oldPass_txt4KeyReleased(evt);
            }
        });
        jPanel4.add(oldPass_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 199, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Confirm Password");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("User Name");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        updatebtn4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        updatebtn4.setForeground(new java.awt.Color(8, 128, 176));
        updatebtn4.setText("Reset Password");
        updatebtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtn4ActionPerformed(evt);
            }
        });
        jPanel4.add(updatebtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 170, 68));

        passNew_txt4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        passNew_txt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passNew_txt4KeyReleased(evt);
            }
        });
        jPanel4.add(passNew_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 199, -1));

        user_txt4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jPanel4.add(user_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 199, -1));

        clearbtn4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        clearbtn4.setForeground(new java.awt.Color(8, 128, 176));
        clearbtn4.setText("clear");
        clearbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtn4ActionPerformed(evt);
            }
        });
        jPanel4.add(clearbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 170, 68));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminPackage/padlock.png"))); // NOI18N
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 90));

        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Reset Password");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 310, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("____________");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmPass_txt4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmPass_txt4KeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_confirmPass_txt4KeyReleased

    private void oldPass_txt4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oldPass_txt4KeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_oldPass_txt4KeyReleased

    private void updatebtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtn4ActionPerformed
        // TODO add your handling code here:
        String userName = user_txt.getText();
        String oldpass = oldPass_txt.getText();
        String newpass = passNew_txt.getText();
        String confirmpass = confirmPass_txt.getText();

        try {
            Connection conn = DatabaseConnectionDoc.setConnection();
            Statement stmt = conn.createStatement();
            String con1 = "SELECT * FROM ADMIN WHERE NAME='"+userName+"'";
            ResultSet rs =stmt.executeQuery(con1);
            while(rs.next())
            {
                String pass = rs.getString("password");
                if(pass.equals(oldpass))
                {
                    JOptionPane.showMessageDialog(rootPane, " oldpassword matches!");
                    if(newpass.equals(confirmpass))
                    {
                        Statement stmt1 = conn.createStatement();
                        String con2 = "update ADMIN set PASSWORD='"+newpass+"'where NAME='"+userName+"'";
                        stmt1.executeUpdate(con2);
                        JOptionPane.showMessageDialog(rootPane, " password is changed succesfully !");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, " confirm passwords dont match");
                    }

                }

                else
                {
                    JOptionPane.showMessageDialog(null, "invalid old password");

                }
            }
		}
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Database error occurred.\n Please return to the Database Manager");
            this.setVisible(false);
        }
    }//GEN-LAST:event_updatebtn4ActionPerformed

    private void passNew_txt4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passNew_txt4KeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_passNew_txt4KeyReleased

    private void clearbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearbtn4ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(admin_change_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(admin_change_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(admin_change_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(admin_change_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new admin_change_pass().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton clearbtn1;
    private javax.swing.JButton clearbtn2;
    private javax.swing.JButton clearbtn3;
    private javax.swing.JButton clearbtn4;
    private javax.swing.JPasswordField confirmPass_txt;
    private javax.swing.JPasswordField confirmPass_txt1;
    private javax.swing.JPasswordField confirmPass_txt2;
    private javax.swing.JPasswordField confirmPass_txt3;
    private javax.swing.JPasswordField confirmPass_txt4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField oldPass_txt;
    private javax.swing.JPasswordField oldPass_txt1;
    private javax.swing.JPasswordField oldPass_txt2;
    private javax.swing.JPasswordField oldPass_txt3;
    private javax.swing.JPasswordField oldPass_txt4;
    private javax.swing.JPasswordField passNew_txt;
    private javax.swing.JPasswordField passNew_txt1;
    private javax.swing.JPasswordField passNew_txt2;
    private javax.swing.JPasswordField passNew_txt3;
    private javax.swing.JPasswordField passNew_txt4;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton updatebtn1;
    private javax.swing.JButton updatebtn2;
    private javax.swing.JButton updatebtn3;
    private javax.swing.JButton updatebtn4;
    private javax.swing.JTextField user_txt;
    private javax.swing.JTextField user_txt1;
    private javax.swing.JTextField user_txt2;
    private javax.swing.JTextField user_txt3;
    private javax.swing.JTextField user_txt4;
    // End of variables declaration//GEN-END:variables
}
