/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminPackage;


import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.PageAttributes;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import userPackage.EntryForm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.TableRowSorter;
import javax.swing.text.JTextComponent;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author DELL
 */
public class admin_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form admin_dashboard
     */
	Connection con;
	DefaultTableModel adminModel, viewDoctors, viewUsers, apptsModel;
	CardLayout cardLayout;
    public admin_dashboard() {
        initComponents();
		con = DatabaseConnectionDoc.setConnection();
		adminModel = (DefaultTableModel) doctorsTableDisplay.getModel();
		viewDoctors = (DefaultTableModel) viewTable.getModel();
		viewUsers = (DefaultTableModel) viewUsersTable.getModel();
		apptsModel = (DefaultTableModel) apptsTable.getModel();
		displayDoctors();
		view_user_appointments();
		AutoCompleteDecorator.decorate(search_cmbBox);
		//*ignore* GUI related code
		userScrollPane.setVisible(false);
		doctorsScrollPane.setVisible(false);
		UIManager.put("OptionPane.messageFont", new Font("Microsoft JhengHei UI", Font.PLAIN, 18));
		homePage_panel.setVisible(true);
		appointment_panel.setVisible(false);
		doctors_panel.setVisible(false);
		users_panel.setVisible(false);
		appts_txt.setVisible(false);
		doctorsTableDisplay.setRowHeight(28);
		viewTable.setRowHeight(28);
		viewUsersTable.setRowHeight(28);
		apptsTable.setRowHeight(28);
		addDoctor_btn.setBackground(Color.white);
		removeDoctor_btn.setBackground(Color.white);
		updateData_btn.setBackground(Color.white);
		viewDoctors_btn.setBackground(Color.white);
		viewUsers_btn.setBackground(Color.white);
		confirmAppt_btn.setBackground(Color.white);
		cancelAppts_btn.setBackground(Color.white);
		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
		this.setSize(screenSize);
    }
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        adminProfile_btn = new javax.swing.JLabel();
        logout_btn = new javax.swing.JLabel();
        viewAllUsers_btn = new javax.swing.JLabel();
        manageAppt_btn = new javax.swing.JLabel();
        manageDoctor_btn = new javax.swing.JLabel();
        manageUsers_btn = new javax.swing.JLabel();
        changePass_btn = new javax.swing.JLabel();
        cards_panel = new javax.swing.JPanel();
        homePage_panel = new javax.swing.JPanel();
        doctorsScrollPane = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        userScrollPane = new javax.swing.JScrollPane();
        viewUsersTable = new javax.swing.JTable();
        viewDoctors_btn = new javax.swing.JButton();
        viewUsers_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        userView_panel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        appointment_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        apptsTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        appt_time_txt = new javax.swing.JTextField();
        patientName_txt = new javax.swing.JTextField();
        doctorName_txt = new javax.swing.JTextField();
        appt_date_txt = new javax.swing.JTextField();
        cancelAppts_btn = new javax.swing.JButton();
        confirmAppt_btn = new javax.swing.JButton();
        doctors_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorsTableDisplay = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        add_radBtn = new javax.swing.JRadioButton();
        remove_radBtn = new javax.swing.JRadioButton();
        update_radBtn = new javax.swing.JRadioButton();
        search_cmbBox = new javax.swing.JComboBox<>();
        search_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        speciality_comboBox = new javax.swing.JComboBox<>();
        fees_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        address_txt = new javax.swing.JTextField();
        appts_txt = new javax.swing.JTextField();
        phone_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addDoctor_btn = new javax.swing.JButton();
        removeDoctor_btn = new javax.swing.JButton();
        apptDays_combo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        fromTime_txt = new javax.swing.JTextField();
        pm_am_lbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        toTime_txt = new javax.swing.JTextField();
        am_pm_lbl = new javax.swing.JLabel();
        updateData_btn = new javax.swing.JButton();
        add_appts_btn = new javax.swing.JButton();
        users_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane2.setBorder(null);
        jSplitPane2.setDividerSize(1);

        jPanel2.setBackground(new java.awt.Color(8, 128, 176));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(adminProfile_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 200, 210));

        logout_btn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminPackage/shutdown.png"))); // NOI18N
        logout_btn.setText(" Logout");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_btnMouseExited(evt);
            }
        });
        jPanel2.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 950, 365, 70));

        viewAllUsers_btn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        viewAllUsers_btn.setForeground(new java.awt.Color(255, 255, 255));
        viewAllUsers_btn.setText(" Home");
        viewAllUsers_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllUsers_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewAllUsers_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewAllUsers_btnMouseExited(evt);
            }
        });
        jPanel2.add(viewAllUsers_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 365, 70));

        manageAppt_btn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        manageAppt_btn.setForeground(new java.awt.Color(255, 255, 255));
        manageAppt_btn.setText(" Manage Appointments");
        manageAppt_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageAppt_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageAppt_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageAppt_btnMouseExited(evt);
            }
        });
        jPanel2.add(manageAppt_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 365, 70));

        manageDoctor_btn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        manageDoctor_btn.setForeground(new java.awt.Color(255, 255, 255));
        manageDoctor_btn.setText(" Manage Doctors");
        manageDoctor_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageDoctor_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageDoctor_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageDoctor_btnMouseExited(evt);
            }
        });
        jPanel2.add(manageDoctor_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 365, 70));

        manageUsers_btn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        manageUsers_btn.setForeground(new java.awt.Color(255, 255, 255));
        manageUsers_btn.setText(" Manage Users");
        manageUsers_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageUsers_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageUsers_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageUsers_btnMouseExited(evt);
            }
        });
        jPanel2.add(manageUsers_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 365, 70));

        changePass_btn.setBackground(new java.awt.Color(255, 255, 255));
        changePass_btn.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 16)); // NOI18N
        changePass_btn.setForeground(new java.awt.Color(255, 255, 255));
        changePass_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changePass_btn.setText("Change password");
        changePass_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePass_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePass_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePass_btnMouseExited(evt);
            }
        });
        jPanel2.add(changePass_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 366, 40));

        jSplitPane2.setLeftComponent(jPanel2);

        cards_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePage_panel.setBackground(new java.awt.Color(255, 255, 255));
        homePage_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewTable.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Speciality", "Fees", "Appointments", "Phone number", "Rating"
            }
        ));
        viewTable.setRowHeight(28);
        viewTable.setSelectionBackground(new java.awt.Color(165, 226, 219));
        viewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTableMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewTableMouseExited(evt);
            }
        });
        doctorsScrollPane.setViewportView(viewTable);

        homePage_panel.add(doctorsScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 1490, 390));

        userScrollPane.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N

        viewUsersTable.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        viewUsersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First name", "Last name", "Gender", "Age", "Phone number", "Secondary phone number", "Address", "Email", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viewUsersTable.setSelectionBackground(new java.awt.Color(165, 226, 219));
        userScrollPane.setViewportView(viewUsersTable);
        if (viewUsersTable.getColumnModel().getColumnCount() > 0) {
            viewUsersTable.getColumnModel().getColumn(0).setResizable(false);
        }

        homePage_panel.add(userScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 1490, 390));

        viewDoctors_btn.setBackground(new java.awt.Color(255, 255, 255));
        viewDoctors_btn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        viewDoctors_btn.setForeground(new java.awt.Color(8, 128, 176));
        viewDoctors_btn.setText("View Doctors");
        viewDoctors_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDoctors_btnActionPerformed(evt);
            }
        });
        homePage_panel.add(viewDoctors_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 174, 50));

        viewUsers_btn.setBackground(new java.awt.Color(255, 255, 255));
        viewUsers_btn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        viewUsers_btn.setForeground(new java.awt.Color(8, 128, 176));
        viewUsers_btn.setText("View Users");
        viewUsers_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUsers_btnActionPerformed(evt);
            }
        });
        homePage_panel.add(viewUsers_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 174, 50));

        jPanel4.setBackground(new java.awt.Color(165, 226, 219));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel14.setText("Online payments weekly");

        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 74)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("53");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(23, 23, 23))
        );

        homePage_panel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, 440, 250));

        jPanel5.setBackground(new java.awt.Color(8, 176, 157));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel17.setText("Appointments for the last week");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 386, -1));
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 74)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("15");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 153, 108));

        userView_panel.setBackground(new java.awt.Color(255, 255, 255));
        userView_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(userView_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 1520, 400));

        homePage_panel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 440, 250));

        jPanel6.setBackground(new java.awt.Color(106, 207, 196));

        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel20.setText("New users monthly registered");

        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 74)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("204");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(121, 121, 121)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(153, 153, 153))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addComponent(jLabel20)
                .addGap(23, 23, 23))
        );

        homePage_panel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 440, 250));

        cards_panel.add(homePage_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1574, 1020));

        appointment_panel.setBackground(new java.awt.Color(255, 255, 255));
        appointment_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        apptsTable.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        apptsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient first name", "Patient last name", "Doctor name", "Date", "Time", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        apptsTable.setPreferredSize(new java.awt.Dimension(525, 525));
        apptsTable.setSelectionBackground(new java.awt.Color(165, 226, 219));
        apptsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apptsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(apptsTable);

        appointment_panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 518, 1420, 390));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel6.setText("Appointment Time");
        appointment_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel10.setText("Patient name");
        appointment_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel13.setText("Doctor name");
        appointment_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel23.setText("Appointment Date");
        appointment_panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        appt_time_txt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        appointment_panel.add(appt_time_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 290, 37));

        patientName_txt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        appointment_panel.add(patientName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 290, 37));

        doctorName_txt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        appointment_panel.add(doctorName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 290, 37));

        appt_date_txt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        appointment_panel.add(appt_date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 290, 37));

        cancelAppts_btn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        cancelAppts_btn.setForeground(new java.awt.Color(8, 128, 176));
        cancelAppts_btn.setText("Cancel");
        cancelAppts_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAppts_btnActionPerformed(evt);
            }
        });
        appointment_panel.add(cancelAppts_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 140, 60));

        confirmAppt_btn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        confirmAppt_btn.setForeground(new java.awt.Color(8, 128, 176));
        confirmAppt_btn.setText("Confirm");
        confirmAppt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAppt_btnActionPerformed(evt);
            }
        });
        appointment_panel.add(confirmAppt_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 140, 60));

        cards_panel.add(appointment_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1579, 1020));

        doctors_panel.setBackground(new java.awt.Color(255, 255, 255));
        doctors_panel.setPreferredSize(new java.awt.Dimension(1574, 1020));
        doctors_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctorsTableDisplay.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        doctorsTableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Speciality", "Fees", "Appointments", "Phone number", "Rating"
            }
        ));
        doctorsTableDisplay.setSelectionBackground(new java.awt.Color(165, 226, 219));
        doctorsTableDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorsTableDisplayMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doctorsTableDisplayMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(doctorsTableDisplay);

        doctors_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 1490, 390));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 20)); // NOI18N
        jLabel1.setText("Choose the action you want to take ");
        doctors_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N
        jLabel11.setText("Search by Speciality");
        doctors_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        add_radBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(add_radBtn);
        add_radBtn.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        add_radBtn.setText("Add Doctor");

        remove_radBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(remove_radBtn);
        remove_radBtn.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        remove_radBtn.setText("Remove Doctor ");

        update_radBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(update_radBtn);
        update_radBtn.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        update_radBtn.setText("Update Doctor data");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(add_radBtn)
                .addGap(49, 49, 49)
                .addComponent(remove_radBtn)
                .addGap(30, 30, 30)
                .addComponent(update_radBtn)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_radBtn)
                    .addComponent(remove_radBtn)
                    .addComponent(update_radBtn))
                .addGap(56, 56, 56))
        );

        doctors_panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 640, 50));

        search_cmbBox.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        search_cmbBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allergy and Immunology", "Audiology", "Cardiology", "Ear, Nose and Throat ", "Endocrinology", "Dermatology", "Dentistry", "Dietitian and Nutrition", "Gastroenterology ", "Genel Surgery", "Hematology", "Hepatology", "Internal Medicine", "IVF and Infertility", "Neurologist", "Oncology", "Opthalmology", "Osteopathy ", "Orthopedics", "Pediatrician", "Physiotherapy", "Psychiatry", "Rheumatology", "Urology", " ", " " }));
        doctors_panel.add(search_cmbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 440, 40));

        search_btn.setBackground(new java.awt.Color(255, 255, 255));
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        doctors_panel.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, 41));

        refresh_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refresh_btnMouseClicked(evt);
            }
        });
        doctors_panel.add(refresh_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 70, 80));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel12.setText("Name");
        doctors_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel2.setText("Speciality");
        doctors_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel3.setText("Fees");
        doctors_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        name_txt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        name_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                name_txtMouseClicked(evt);
            }
        });
        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        doctors_panel.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 310, 37));

        speciality_comboBox.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        speciality_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allergy and Immunology", "Audiology", "Cardiology", "Ear, Nose and Throat ", "Endocrinology", "Dermatology", "Dentistry", "Dietitian and Nutrition", "Gastroenterology ", "Genel Surgery", "Hematology", "Hepatology", "Internal Medicine", "IVF and Infertility", "Neurologist", "Oncology", "Opthalmology", "Osteopathy ", "Orthopedics", "Pediatrician", "Physiotherapy", "Psychiatry", "Rheumatology", "Urology", " ", " " }));
        doctors_panel.add(speciality_comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 310, 37));

        fees_txt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        doctors_panel.add(fees_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 210, 37));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel5.setText("Address");
        doctors_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel7.setText("Appointments");
        doctors_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, -1));

        address_txt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        doctors_panel.add(address_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, 480, 37));

        appts_txt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        doctors_panel.add(appts_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 480, 40));

        phone_txt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        doctors_panel.add(phone_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, 180, 37));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel4.setText("Phone Number");
        doctors_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, -1, -1));

        addDoctor_btn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        addDoctor_btn.setForeground(new java.awt.Color(8, 128, 176));
        addDoctor_btn.setText("Add");
        addDoctor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDoctor_btnActionPerformed(evt);
            }
        });
        doctors_panel.add(addDoctor_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 140, 50));

        removeDoctor_btn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        removeDoctor_btn.setForeground(new java.awt.Color(8, 128, 176));
        removeDoctor_btn.setText("Remove");
        removeDoctor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDoctor_btnActionPerformed(evt);
            }
        });
        doctors_panel.add(removeDoctor_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 480, 140, 50));

        apptDays_combo.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        apptDays_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturdays", "Sundays", "Mondays", "Tuesdays", "Wednesdays", "Thrusdays", "Fridays", "All Weekdays Except..." }));
        doctors_panel.add(apptDays_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 180, 37));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel8.setText("from");
        doctors_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 360, -1, -1));

        fromTime_txt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        fromTime_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromTime_txtActionPerformed(evt);
            }
        });
        doctors_panel.add(fromTime_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 350, 50, 37));

        pm_am_lbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        pm_am_lbl.setForeground(new java.awt.Color(102, 102, 255));
        pm_am_lbl.setText("PM");
        pm_am_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pm_am_lblMouseClicked(evt);
            }
        });
        doctors_panel.add(pm_am_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        jLabel9.setText("to");
        doctors_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 360, -1, -1));

        toTime_txt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        toTime_txt.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        toTime_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTime_txtActionPerformed(evt);
            }
        });
        doctors_panel.add(toTime_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 350, 50, 37));

        am_pm_lbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        am_pm_lbl.setForeground(new java.awt.Color(102, 102, 255));
        am_pm_lbl.setText("AM");
        am_pm_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                am_pm_lblMouseClicked(evt);
            }
        });
        doctors_panel.add(am_pm_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 360, -1, -1));

        updateData_btn.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        updateData_btn.setForeground(new java.awt.Color(8, 128, 176));
        updateData_btn.setText("Update");
        updateData_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateData_btnActionPerformed(evt);
            }
        });
        doctors_panel.add(updateData_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 480, 140, 50));

        add_appts_btn.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        add_appts_btn.setForeground(new java.awt.Color(8, 128, 176));
        add_appts_btn.setText("Add");
        add_appts_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_appts_btnActionPerformed(evt);
            }
        });
        doctors_panel.add(add_appts_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 80, 40));

        cards_panel.add(doctors_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1574, 1020));

        users_panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout users_panelLayout = new javax.swing.GroupLayout(users_panel);
        users_panel.setLayout(users_panelLayout);
        users_panelLayout.setHorizontalGroup(
            users_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1574, Short.MAX_VALUE)
        );
        users_panelLayout.setVerticalGroup(
            users_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );

        cards_panel.add(users_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1574, 1020));

        jSplitPane2.setRightComponent(cards_panel);

        jPanel1.add(jSplitPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1940, 1020));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1940, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	public void displayDoctors(){
		try{
			Statement displayStat = con.createStatement();
			String displaySql = "select * from Doctors";
			ResultSet rs = displayStat.executeQuery(displaySql);
			while(rs.next()){
				String name = rs.getString("name");
				String address = rs.getString("address");
				String speciality = rs.getString("speciality");
				String fees = String.valueOf(rs.getInt("fees"));
				String appointments = rs.getString("appointments");
				String phoneNum = String.valueOf(rs.getInt("phoneno"));
				String rating = String.valueOf(rs.getDouble("rating"));
				//string array to store data into jtable
				String doctorData[] = {name, address, speciality, fees, appointments, phoneNum, rating};
				adminModel.addRow(doctorData);
			}
		}
		catch(SQLException exp){
			JOptionPane.showMessageDialog(this, exp.toString());
		}
	}
	public String getDoctorNameFromDB(int doctor_id){
		try{
			Statement getDocname = con.createStatement();
			String getDoctorName = "select name from doctors where id = "+doctor_id+"";
			ResultSet docName = getDocname.executeQuery(getDoctorName);
			while(docName.next()){
				String doctor_name = docName.getString("name");
				return doctor_name;
			}
		}
		catch(SQLException ex){
			JOptionPane.showMessageDialog(this, "Database error occurred.\n Please return to the Database Manager");
		}
		return null;
	}
	public String getUserFNameFromDB(int patient_id){
		try{
			Statement getUsername = con.createStatement();
			String getPatientName = "select fname from user1 where id = "+patient_id+"";
			ResultSet patName = getUsername.executeQuery(getPatientName);
			while(patName.next()){
				String first_name = patName.getString("fname");
				return first_name;
			}
		}
		catch(SQLException ex){
			JOptionPane.showMessageDialog(this, "Database error occurred.\n Please return to the Database Manager");
		}
		return null;
	}
	public String getUserLNameFromDB(int patient_id){
		try{
			Statement getUsername = con.createStatement();
			String getPatientName = "select lname from user1 where id = "+patient_id+"";
			ResultSet patName = getUsername.executeQuery(getPatientName);
			while(patName.next()){
				String last_name = patName.getString("lname");
				return last_name;
			}
		}
		catch(SQLException ex){
			JOptionPane.showMessageDialog(this, "Database error occurred.\n Please return to the Database Manager");
		}
		return null;
	}
	public void view_user_appointments(){
		Statement viewApptsStat = null;
		String viewApptsSql;
		try{
			viewApptsStat = con.createStatement();
			viewApptsSql = "Select * from appointments";
			ResultSet appts = viewApptsStat.executeQuery(viewApptsSql);
			while(appts.next()){
				String date = String.valueOf(appts.getDate("date"));
				String time = appts.getString("time");
				int patient_id = appts.getInt("patient_id");
				int doctor_id = appts.getInt("doctor_id");
				String appt_status = appts.getString("status");
				String patient_fname = getUserFNameFromDB(patient_id);
				String patient_lname = getUserLNameFromDB(patient_id);
				String doctor_name = getDoctorNameFromDB(doctor_id);
				String apptsArr[] = {patient_fname,patient_lname, doctor_name, date, time, appt_status};
				apptsModel.addRow(apptsArr);
			}
		}
		catch(SQLException ex){
			JOptionPane.showMessageDialog(this, "Database error occurred.\n Please return to the Database Manager");
		}
	}
    private void viewAllUsers_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllUsers_btnMouseClicked
        // TODO add your handling code here:
		homePage_panel.setVisible(true);
		appointment_panel.setVisible(false);
		doctors_panel.setVisible(false);
		users_panel.setVisible(false);
		
    }//GEN-LAST:event_viewAllUsers_btnMouseClicked

    private void manageAppt_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAppt_btnMouseClicked
        // TODO add your handling code here:
		homePage_panel.setVisible(false);
		appointment_panel.setVisible(true);
		doctors_panel.setVisible(false);
		users_panel.setVisible(false);
    }//GEN-LAST:event_manageAppt_btnMouseClicked

    private void manageDoctor_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageDoctor_btnMouseClicked
        // TODO add your handling code here:
		homePage_panel.setVisible(false);
		appointment_panel.setVisible(false);
		doctors_panel.setVisible(true);
		users_panel.setVisible(false);
    }//GEN-LAST:event_manageDoctor_btnMouseClicked

    private void manageUsers_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUsers_btnMouseClicked
        // TODO add your handling code here:
		homePage_panel.setVisible(false);
		appointment_panel.setVisible(false);
		doctors_panel.setVisible(false);
		users_panel.setVisible(true);
    }//GEN-LAST:event_manageUsers_btnMouseClicked

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        // TODO add your handling code here:
		new EntryForm().setVisible(true);
		this.setVisible(false);
    }//GEN-LAST:event_logout_btnMouseClicked

    private void viewAllUsers_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllUsers_btnMouseExited
        // TODO add your handling code here:
		viewAllUsers_btn.setBackground(new Color(8,128,176));
    }//GEN-LAST:event_viewAllUsers_btnMouseExited

    private void manageAppt_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAppt_btnMouseEntered
        // TODO add your handling code here:
		manageAppt_btn.setBackground(new Color(82,166,199));
		manageAppt_btn.setOpaque(true);
    }//GEN-LAST:event_manageAppt_btnMouseEntered

    private void manageAppt_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAppt_btnMouseExited
        // TODO add your handling code here:
		manageAppt_btn.setBackground(new Color(8,128,176));
    }//GEN-LAST:event_manageAppt_btnMouseExited

    private void manageDoctor_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageDoctor_btnMouseEntered
        // TODO add your handling code here:
		manageDoctor_btn.setBackground(new Color(82,166,199));
		manageDoctor_btn.setOpaque(true);
    }//GEN-LAST:event_manageDoctor_btnMouseEntered

    private void manageDoctor_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageDoctor_btnMouseExited
        // TODO add your handling code here:\
		manageDoctor_btn.setBackground(new Color(8,128,176));
    }//GEN-LAST:event_manageDoctor_btnMouseExited

    private void manageUsers_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUsers_btnMouseEntered
        // TODO add your handling code here:
		manageUsers_btn.setBackground(new Color(82,166,199));
		manageUsers_btn.setOpaque(true);
    }//GEN-LAST:event_manageUsers_btnMouseEntered

    private void manageUsers_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUsers_btnMouseExited
        // TODO add your handling code here:
		manageUsers_btn.setBackground(new Color(8,128,176));
    }//GEN-LAST:event_manageUsers_btnMouseExited

    private void logout_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseEntered
        // TODO add your handling code here:
		logout_btn.setBackground(new Color(243,66,53));
		logout_btn.setOpaque(true);
    }//GEN-LAST:event_logout_btnMouseEntered

    private void logout_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseExited
        // TODO add your handling code here:
		logout_btn.setBackground(new Color(8,128,176));
    }//GEN-LAST:event_logout_btnMouseExited

    private void toTime_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTime_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toTime_txtActionPerformed

    private void fromTime_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromTime_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromTime_txtActionPerformed

    private void pm_am_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pm_am_lblMouseClicked
        // TODO add your handling code here:
		if(pm_am_lbl.getText().equalsIgnoreCase("PM")){
			pm_am_lbl.setText("AM");
		}
		else{
			pm_am_lbl.setText("PM");
		}
    }//GEN-LAST:event_pm_am_lblMouseClicked

    private void am_pm_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_am_pm_lblMouseClicked
        // TODO add your handling code here:
		if(am_pm_lbl.getText().equalsIgnoreCase("AM")){
			am_pm_lbl.setText("PM");
		}
		else{
			am_pm_lbl.setText("AM");
		}
    }//GEN-LAST:event_am_pm_lblMouseClicked

    private void doctorsTableDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsTableDisplayMouseClicked
        // TODO add your handling code here:
		appts_txt.setVisible(true);
		name_txt.setText(adminModel.getValueAt(doctorsTableDisplay.getSelectedRow(),0).toString());
		speciality_comboBox.setSelectedItem(adminModel.getValueAt(doctorsTableDisplay.getSelectedRow(),2).toString());
		fees_txt.setText(adminModel.getValueAt(doctorsTableDisplay.getSelectedRow(),3).toString());
		address_txt.setText(adminModel.getValueAt(doctorsTableDisplay.getSelectedRow(),1).toString());
		appts_txt.setText(adminModel.getValueAt(doctorsTableDisplay.getSelectedRow(),4).toString());
		phone_txt.setText(adminModel.getValueAt(doctorsTableDisplay.getSelectedRow(),5).toString());
    }//GEN-LAST:event_doctorsTableDisplayMouseClicked

    private void doctorsTableDisplayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsTableDisplayMouseExited
        // TODO add your handling code here:
		appts_txt.setVisible(true);
    }//GEN-LAST:event_doctorsTableDisplayMouseExited

    private void name_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_txtMouseClicked
        // TODO add your handling code here:
		
    }//GEN-LAST:event_name_txtMouseClicked
	
    private void updateData_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateData_btnActionPerformed
        // TODO add your handling code here:
		if(doctorsTableDisplay.getSelectedRowCount() == 1){
			
			try{
				//Connection con = DatabaseConnectionDoc.setConnection();
				Statement updateStat = con.createStatement();
				String spec = speciality_comboBox.getSelectedItem().toString();
				String updateSQL = "update doctors set address = '"+address_txt.getText()+"', speciality = '"+spec+"', fees= "+fees_txt.getText()+", phoneno= "+phone_txt.getText()+"where name like '"+name_txt.getText()+"'";
				updateStat.executeUpdate(updateSQL);
				adminModel.setRowCount(0);
				displayDoctors();
				JOptionPane.showMessageDialog(this, "Doctor information updated successfully.");
			}
			catch(SQLException ex){
				JOptionPane.showMessageDialog(this, "Database error occurred.\n Please return to the Database Manager");
			}
		}
    }//GEN-LAST:event_updateData_btnActionPerformed

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:

		if(add_radBtn.isSelected()){
			name_txt.setText("");
			fees_txt.setText("");
			address_txt.setText("");
			phone_txt.setText("");
			name_txt.setEditable(true);
			name_txt.setBackground(Color.white);
			removeDoctor_btn.setVisible(false);
			addDoctor_btn.setVisible(true);
			updateData_btn.setVisible(false);
		}
		else if(remove_radBtn.isSelected()){
			
			name_txt.setEditable(false);
			name_txt.setBackground(new Color(234,234,234));
			removeDoctor_btn.setVisible(true);
			addDoctor_btn.setVisible(false);
			updateData_btn.setVisible(false);
		}
		else if(update_radBtn.isSelected()){
			
			name_txt.setEditable(false);
			name_txt.setBackground(new Color(234,234,234));
			removeDoctor_btn.setVisible(false);
			addDoctor_btn.setVisible(false);
			updateData_btn.setVisible(true);
		}
		
    }//GEN-LAST:event_jPanel3MouseEntered

    private void addDoctor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDoctor_btnActionPerformed
        // TODO add your handling code here:
		try{
            //Connection con = DatabaseConnectionDoc.setConnection();
            Statement addStat = con.createStatement();
            String addSql = "insert into doctors values('"+"Dr. "+name_txt.getText()+"', '"+address_txt.getText()+"', '"+speciality_comboBox.getSelectedItem().toString()+"',"+fees_txt.getText()+", '"+apptDays_combo.getSelectedItem().toString()+" from "+fromTime_txt.getText()+pm_am_lbl.getText()+" to "+toTime_txt.getText()+am_pm_lbl.getText()+"', "+phone_txt.getText()+","+"0"+")";
            addStat.executeUpdate(addSql);
            displayDoctors();
			
        }
        catch(SQLException exp){
			JOptionPane.showMessageDialog(this, "Database error occurred.\n Please return to the Database Manager");
        }
    }//GEN-LAST:event_addDoctor_btnActionPerformed

    private void removeDoctor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDoctor_btnActionPerformed
        // TODO add your handling code here:
		try{
			//Connection con = DatabaseConnectionDoc.setConnection();
			Statement removeStat = con.createStatement();
			String removeSql = "delete from doctors where name like '"+name_txt.getText()+"'";
			removeStat.executeUpdate(removeSql);
			displayDoctors();
			
		}
		catch(SQLException ex){
			JOptionPane.showMessageDialog(this, "Database error occurred.\n Please return to the Database Manager");
		}
    }//GEN-LAST:event_removeDoctor_btnActionPerformed

    private void viewAllUsers_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllUsers_btnMouseEntered
        // TODO add your handling code here:
		viewAllUsers_btn.setBackground(new Color(82,166,199));
		viewAllUsers_btn.setOpaque(true);
    }//GEN-LAST:event_viewAllUsers_btnMouseEntered

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
		DefaultTableModel searchModel = (DefaultTableModel) doctorsTableDisplay.getModel();
		String searchedItem = search_cmbBox.getSelectedItem().toString();
		TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(searchModel);
		doctorsTableDisplay.setRowSorter(trs);
		trs.setRowFilter(javax.swing.RowFilter.regexFilter(searchedItem));
		if(doctorsTableDisplay.getRowCount()==0){
			JOptionPane.showMessageDialog(this, "No doctors in this speciality yet.");
		}
    }//GEN-LAST:event_search_btnActionPerformed

    private void viewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTableMouseClicked

    private void viewTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTableMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTableMouseExited

    private void refresh_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_btnMouseClicked
        // TODO add your handling code here:
		TableRowSorter<DefaultTableModel> viewTableSorter = new TableRowSorter<DefaultTableModel>(adminModel);
		doctorsTableDisplay.setRowSorter(viewTableSorter);
    }//GEN-LAST:event_refresh_btnMouseClicked

    private void viewDoctors_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDoctors_btnActionPerformed
        // TODO add your handling code here:
		userScrollPane.setVisible(false);
		doctorsScrollPane.setVisible(true);
		try{
			Statement displayStat = con.createStatement();
			String displaySql = "select * from Doctors";
			ResultSet rs = displayStat.executeQuery(displaySql);
			while(rs.next()){
				String name = rs.getString("name");
				String address = rs.getString("address");
				String speciality = rs.getString("speciality");
				String fees = String.valueOf(rs.getInt("fees"));
				String appointments = rs.getString("appointments");
				String phoneNum = String.valueOf(rs.getInt("phoneno"));
				String rating = String.valueOf(rs.getDouble("rating"));
				//string array to store data into jtable
				String doctorData[] = {name, address, speciality, fees, appointments, phoneNum, rating};
				viewDoctors.addRow(doctorData);
			}
		}
		catch(SQLException exp){
			JOptionPane.showMessageDialog(this, "Database error occurred.\n Please return to the Database Manager");
		}
    }//GEN-LAST:event_viewDoctors_btnActionPerformed

    private void changePass_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePass_btnMouseEntered
        // TODO add your handling code here:
		changePass_btn.setBackground(new Color(82,166,199));
		changePass_btn.setOpaque(true);
    }//GEN-LAST:event_changePass_btnMouseEntered

    private void changePass_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePass_btnMouseExited
        // TODO add your handling code here:
		changePass_btn.setBackground(new Color(8,128,176));
    }//GEN-LAST:event_changePass_btnMouseExited

    private void changePass_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePass_btnMouseClicked
        // TODO add your handling code here:
		new admin_change_pass().setVisible(true);
    }//GEN-LAST:event_changePass_btnMouseClicked

    private void viewUsers_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUsers_btnActionPerformed
        // TODO add your handling code here:
		userScrollPane.setVisible(true);
		doctorsScrollPane.setVisible(false);
		try{
			Statement viewUsersStat = con.createStatement();
			String viewSql = "select * from user1";
			ResultSet rs = viewUsersStat.executeQuery(viewSql);
			while(rs.next()){
				int id = rs.getInt("id");
				String first_name = rs.getString("fname");
				String last_name = rs.getString("lname");
				String gender = rs.getString("gender");
				String age = String.valueOf(rs.getInt("age"));
				String phoneno_1 = String.valueOf(rs.getInt("phoneno1"));
				String phoneno_2 = String.valueOf(rs.getInt("phoneno2"));
				if(phoneno_1 == null || phoneno_2 == null){
					phoneno_1 = "-";
					phoneno_2 = "-";
				}
				String user_address = rs.getString("address");
				String email = rs.getString("email");
				String password = "Data Encrypted";
				//string array to store data into jtable
				String userData[] = {first_name, last_name, gender, age, phoneno_1, phoneno_2, user_address, email, password};
				viewUsers.addRow(userData);
			}
		}
		catch(SQLException exp){
			JOptionPane.showMessageDialog(this, "Database error occurred.\n Please return to the Database Manager");
		}
    }//GEN-LAST:event_viewUsers_btnActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void apptsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apptsTableMouseClicked
        // TODO add your handling code here:
		patientName_txt.setText(apptsModel.getValueAt(apptsTable.getSelectedRow(),0).toString()+" "+ apptsModel.getValueAt(apptsTable.getSelectedRow(), 1).toString());
		doctorName_txt.setText(apptsModel.getValueAt(apptsTable.getSelectedRow(),2).toString());
		appt_date_txt.setText(apptsModel.getValueAt(apptsTable.getSelectedRow(),3).toString());
		appt_time_txt.setText(apptsModel.getValueAt(apptsTable.getSelectedRow(),4).toString());
    }//GEN-LAST:event_apptsTableMouseClicked

    private void confirmAppt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAppt_btnActionPerformed
        // TODO add your handling code here:
		Statement st = null;
		Statement another = null;
		String sql, selectSql;
		String userFirstName = apptsModel.getValueAt(apptsTable.getSelectedRow(),0).toString();
		try{
			st = con.createStatement();
			another = con.createStatement();
			selectSql = "select id from user1 where fname like '"+userFirstName+"'";
			ResultSet rs = st.executeQuery(selectSql);
			while(rs.next()){
				int pt_id = rs.getInt("id");
				sql = "update appointments set status = 'CONFIRMED' where patient_id = "+pt_id+"";
				another.executeUpdate(sql);
				//apptsModel.fireTableCellUpdated(apptsTable.getSelectedRow(), 5);
				apptsModel.setRowCount(0);
				view_user_appointments();
			}
			con.setAutoCommit(false);
		}
		catch(SQLException ex){
			JOptionPane.showMessageDialog(this, "Database error occurred.\n Please return to the Database Manager");
		}
    }//GEN-LAST:event_confirmAppt_btnActionPerformed

    private void cancelAppts_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAppts_btnActionPerformed
        // TODO add your handling code here:
		Statement st = null;
		Statement another = null;
		String sql, selectSql;
		String userFirstName = apptsModel.getValueAt(apptsTable.getSelectedRow(),0).toString();
		try{
			st = con.createStatement();
			another = con.createStatement();
			selectSql = "select id from user1 where fname like '"+userFirstName+"'";
			ResultSet rs = st.executeQuery(selectSql);
			while(rs.next()){
				int pt_id = rs.getInt("id");
				sql = "update appointments set status = 'CANCELLED' where patient_id = "+pt_id+"";
				another.executeUpdate(sql);
				apptsModel.setRowCount(0);
				view_user_appointments();
			}
			con.setAutoCommit(false);
		}
		catch(SQLException ex){
			JOptionPane.showMessageDialog(this, "Database error occurred.\n Please return to the Database Manager");
		}
    }//GEN-LAST:event_cancelAppts_btnActionPerformed

    private void add_appts_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_appts_btnActionPerformed
        // TODO add your handling code here:
      if(doctorsTableDisplay.getSelectedRowCount() == 1){
			
			try{
				//Connection con = DatabaseConnectionDoc.setConnection();
				Statement updateStat = con.createStatement();
				String spec = speciality_comboBox.getSelectedItem().toString();
				String updateSQL = "update doctors set address = '"+address_txt.getText()+"', speciality = '"+spec+"', fees= "+fees_txt.getText()+", phoneno= "+phone_txt.getText()+"where name like '"+name_txt.getText()+", APPOINTME= "+appts_txt.getText()+"'";
				updateStat.executeUpdate(updateSQL);
				adminModel.setRowCount(0);
				displayDoctors();
				JOptionPane.showMessageDialog(this, "Doctor information updated successfully.");
			}
			catch(SQLException ex){
				JOptionPane.showMessageDialog(this, "Database error occurred.\n Please return to the Database Manager");
			}
		}
    }//GEN-LAST:event_add_appts_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDoctor_btn;
    private javax.swing.JButton add_appts_btn;
    private javax.swing.JRadioButton add_radBtn;
    private javax.swing.JTextField address_txt;
    private javax.swing.JLabel adminProfile_btn;
    private javax.swing.JLabel am_pm_lbl;
    private javax.swing.JPanel appointment_panel;
    private javax.swing.JComboBox<String> apptDays_combo;
    private javax.swing.JTextField appt_date_txt;
    private javax.swing.JTextField appt_time_txt;
    private javax.swing.JTable apptsTable;
    private javax.swing.JTextField appts_txt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelAppts_btn;
    private javax.swing.JPanel cards_panel;
    private javax.swing.JLabel changePass_btn;
    private javax.swing.JButton confirmAppt_btn;
    private javax.swing.JTextField doctorName_txt;
    private javax.swing.JScrollPane doctorsScrollPane;
    private javax.swing.JTable doctorsTableDisplay;
    private javax.swing.JPanel doctors_panel;
    private javax.swing.JTextField fees_txt;
    private javax.swing.JTextField fromTime_txt;
    private javax.swing.JPanel homePage_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel logout_btn;
    private javax.swing.JLabel manageAppt_btn;
    private javax.swing.JLabel manageDoctor_btn;
    private javax.swing.JLabel manageUsers_btn;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField patientName_txt;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JLabel pm_am_lbl;
    private javax.swing.JLabel refresh_btn;
    private javax.swing.JButton removeDoctor_btn;
    private javax.swing.JRadioButton remove_radBtn;
    private javax.swing.JButton search_btn;
    private javax.swing.JComboBox<String> search_cmbBox;
    private javax.swing.JComboBox<String> speciality_comboBox;
    private javax.swing.JTextField toTime_txt;
    private javax.swing.JButton updateData_btn;
    private javax.swing.JRadioButton update_radBtn;
    private javax.swing.JScrollPane userScrollPane;
    private javax.swing.JPanel userView_panel;
    private javax.swing.JPanel users_panel;
    private javax.swing.JLabel viewAllUsers_btn;
    private javax.swing.JButton viewDoctors_btn;
    private javax.swing.JTable viewTable;
    private javax.swing.JTable viewUsersTable;
    private javax.swing.JButton viewUsers_btn;
    // End of variables declaration//GEN-END:variables
}
