/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminPackage;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HI-TECH
 */
public class ChangePass extends javax.swing.JFrame {

    /**
     * Creates new form ChangePass
     */
    //String Username;
    public ChangePass() {
        initComponents();
        DatabaseConnectionDoc.setConnection();
        
    }
    /*public ChangePass(String name) {
        initComponents();
        Username = name;
        updatebtn.setEnabled(false);
        
    }*/
    public void validateField()
    {
        String oldpass = oldPass_txt.getText();
        String newpass = passNew_txt.getText();
        String confirmpass = confirmPass_txt.getText();
        if(!oldpass.equals("") && !newpass.equals("") && !confirmpass.equals("") && newpass.equals(confirmpass))
        {
            updatebtn.setEnabled(true);
        }
        else
        {
            updatebtn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        confirmPass_txt = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        oldPass_txt = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        passNew_txt = new javax.swing.JPasswordField();
        user_txt = new javax.swing.JTextField();
        clearbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reseet Pass", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Old password");

        confirmPass_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        confirmPass_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                confirmPass_txtKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("New Password");

        oldPass_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        oldPass_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oldPass_txtKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Confirm Password");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("User Name");

        updatebtn.setText("Reset Password");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        passNew_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passNew_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passNew_txtKeyReleased(evt);
            }
        });

        user_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        user_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_txtActionPerformed(evt);
            }
        });
        user_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                user_txtKeyReleased(evt);
            }
        });

        clearbtn.setText("clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passNew_txt)
                            .addComponent(confirmPass_txt)
                            .addComponent(oldPass_txt)
                            .addComponent(user_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(updatebtn)
                        .addGap(27, 27, 27)
                        .addComponent(clearbtn)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passNew_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(confirmPass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatebtn)
                    .addComponent(clearbtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_txtActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        /*String oldpass = oldPass_txt.getText();
        String newpass = passNew_txt.getText();
        String confirmpass = confirmPass_txt.getText();
        Admin.changePassword(Username, oldpass, newpass);
        setVisible(false);
        new ChangePass(Username).setVisible(true);*/

        String userName = user_txt.getText();
        String oldpass = oldPass_txt.getText();
        String newpass = passNew_txt.getText();
        String confirmpass = confirmPass_txt.getText();

          try {
              Connection conn = DatabaseConnectionDoc.setConnection();
               Statement stmt = conn.createStatement();
               String con1 = "SELECT * FROM ADMIN WHERE NAME='"+userName+"'"; 
               ResultSet rs =stmt.executeQuery(con1); 
                //DatabaseConnectionDoc.rs = DatabaseConnectionDoc.stmt.executeQuery(con1);
                while(rs.next())
                {
                    String pass = rs.getString("password");
                    if(pass.equals(oldpass))
                    {
                       JOptionPane.showMessageDialog(rootPane, " oldpassword matches!");
                    if(newpass.equals(confirmpass))
                    {
                        Statement stmt1 = conn.createStatement();
                        String con2 = "update ADMIN set PASSWORD='"+newpass+"'where NAME='"+userName+"'";
                       stmt1.executeUpdate(con2);
                        JOptionPane.showMessageDialog(rootPane, " password is changed succesfully !");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, " confirm passwords dont match");
                    }
                    
                    }
                    
                else
                {
                     JOptionPane.showMessageDialog(null, "invalid old password");

                }
                }
               /* if(pass.equals(oldpass))
                {
                    if(newpass.equals(confirmpass))
                    {
                        
                        DatabaseConnectionDoc.stmt.executeUpdate(con2);
                        JOptionPane.showMessageDialog(rootPane, " password is changed succesfully !");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, " confirm passwords dont match");
                    }
                }
                else
                {
                                            JOptionPane.showMessageDialog(null, "invalid old password");

                }
                */
            }
    
        catch (SQLException e) {
                                                    JOptionPane.showMessageDialog(null, " wrong shit");
                                                                            this.setVisible(false);

                                                    

        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
       /* setVisible(false);
        new ChangePass(Username).setVisible(true);*/
        
    }//GEN-LAST:event_clearbtnActionPerformed

    private void user_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_txtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_user_txtKeyReleased

    private void oldPass_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oldPass_txtKeyReleased
        // TODO add your handling code here:
       validateField();
    }//GEN-LAST:event_oldPass_txtKeyReleased

    private void passNew_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passNew_txtKeyReleased
        // TODO add your handling code here:
                validateField();

    }//GEN-LAST:event_passNew_txtKeyReleased

    private void confirmPass_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmPass_txtKeyReleased
        // TODO add your handling code here:
                validateField();

    }//GEN-LAST:event_confirmPass_txtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JPasswordField confirmPass_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField oldPass_txt;
    private javax.swing.JPasswordField passNew_txt;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField user_txt;
    // End of variables declaration//GEN-END:variables
}
